// Auto-generated API content
// Do not edit this file manually - it will be overwritten

export const generatedApiContent = {
	playermanager: {
		title: "PlayerManager",
		description: "The main class for managing players across multiple Discord guilds.",
		summary: "",
		badges: ["class", "core", "playermanager"],
		code: '// Basic setup with plugins and extensions\nconst manager = new PlayerManager({\n  plugins: [\n    new YouTubePlugin(),\n    new SoundCloudPlugin(),\n    new SpotifyPlugin(),\n    new TTSPlugin({ defaultLang: "en" })\n  ],\n  extensions: [\n    new voiceExt(null, { lang: "en-US" }),\n    new lavalinkExt(null, {\n      nodes: [{ host: "localhost", port: 2333, password: "youshallnotpass" }]\n    })\n  ],\n  extractorTimeout: 10000,\n  autoCleanup: true,\n  cleanupInterval: 60000\n});\n// Create a player for a guild\nconst player = await manager.create(guildId, {\n  tts: { interrupt: true, volume: 1 },\n  leaveOnEnd: true,\n  leaveTimeout: 30000\n});\n// Get existing player\nconst existingPlayer = manager.get(guildId);\nif (existingPlayer) {\n  await existingPlayer.play("Never Gonna Give You Up", userId);\n}',
		methods: [
			{
				name: "create",
				signature: "async create(guildOrId: string | { id: string }, options?: PlayerOptions): Promise<Player>",
				description: "Create a new player for a guild /",
				example: "",
				code: "",
				parameters: [
					{
						name: "guildOrId",
						type: "string | { id: string }",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "options?",
						type: "PlayerOptions",
						description: "",
						optional: true,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "Promise<Player>",
					description: "The created player instance",
				},
			},
			{
				name: "get",
				signature: "get(guildOrId: string | { id: string }): Player | undefined",
				description: "Get an existing player for a guild /",
				example: "",
				code: "",
				parameters: [
					{
						name: "guildOrId",
						type: "string | { id: string }",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "Player | undefined",
					description: "The player instance or undefined if not found",
				},
			},
			{
				name: "getPlayer",
				signature: "getPlayer(guildOrId: string | { id: string }): Player | undefined",
				description: "Get an existing player for a guild (alias for get) /",
				example: "",
				code: "",
				parameters: [
					{
						name: "guildOrId",
						type: "string | { id: string }",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "Player | undefined",
			},
			{
				name: "getall",
				signature: "getall(): Player[]",
				description: "Alias for getAll /",
				example: "",
				code: "",
				parameters: [],
				returns: "Player[]",
			},
			{
				name: "delete",
				signature: "delete(guildOrId: string | { id: string }): boolean",
				description: "Destroy a player and clean up resources /",
				example: "",
				code: "",
				parameters: [
					{
						name: "guildOrId",
						type: "string | { id: string }",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "boolean",
					description: "True if player was destroyed, false if not found",
				},
			},
			{
				name: "has",
				signature: "has(guildOrId: string | { id: string }): boolean",
				description: "Check if a player exists for a guild /",
				example: "",
				code: "",
				parameters: [
					{
						name: "guildOrId",
						type: "string | { id: string }",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "boolean",
					description: "True if player exists",
				},
			},
			{
				name: "destroy",
				signature: "destroy(): void",
				description: "Destroy all players and clean up /",
				example: "",
				code: "",
				parameters: [],
				returns: "void",
			},
			{
				name: "search",
				signature: "async search(query: string, requestedBy: string): Promise<SearchResult>",
				description:
					"Search via an internal Player instance (all registered plugins) without storing it in {@link players}. Uses the same search pipeline as {@link Player.search}: extension hooks, plugin deduplication, scoring, and fallback handling. /",
				example: "",
				code: "",
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "requestedBy",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "Promise<SearchResult>",
					description: "",
				},
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	managercacheentry: {
		title: "ManagerCacheEntry",
		description:
			'/** Guild id for the internal search-only player (never stored in {@link PlayerManager.players}). */ const SEARCH_PLAYER_GUILD_ID = "__ziplayer_search__"; export const getGlobalManager = (): PlayerManager | null => { try { const instance = (globalThis as any)[GLOBAL_MANAGER_KEY]; if (!instance) { return null; } return instance as PlayerManager; } catch (error) { console.error("[PlayerManager] Error getting global instance:", error); return null; } }; const setGlobalManager = (instance: PlayerManager): void => { try { (globalThis as any)[GLOBAL_MANAGER_KEY] = instance; } catch (error) { console.error("[PlayerManager] Error setting global instance:", error); } }; export declare interface PlayerManager { on<K extends keyof ManagerEvents>(event: K, listener: (...args: ManagerEvents[K]) => void): this; emit<K extends keyof ManagerEvents>(event: K, ...args: ManagerEvents[K]): boolean; }',
		summary: "",
		badges: ["interface", "core", "managercacheentry"],
		code: "// ManagerCacheEntry usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	player: {
		title: "Player",
		description: "The Player class",
		summary: "",
		badges: ["class", "core", "player"],
		code: "// Player usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
	},
	queue: {
		title: "Queue",
		description: "The Queue class",
		summary: "",
		badges: ["class", "core", "queue"],
		code: "// Queue usage example",
		methods: [
			{
				name: "add",
				signature: "add(track: Track): number",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "track",
						type: "Track",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "number",
			},
			{
				name: "remove",
				signature: "remove(index: number): Track | null",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "index",
						type: "number",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "Track | null",
			},
			{
				name: "clear",
				signature: "clear(): void",
				description: "",
				example: "",
				code: "",
				parameters: [],
				returns: "void",
			},
			{
				name: "autoPlay",
				signature: "autoPlay(value?: boolean): boolean",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "value?",
						type: "boolean",
						description: "",
						optional: true,
						default: "",
						variation: "",
					},
				],
				returns: "boolean",
			},
			{
				name: "shuffle",
				signature: "shuffle(): void",
				description: "",
				example: "",
				code: "",
				parameters: [],
				returns: "void",
			},
			{
				name: "has",
				signature: "has(identifier: string | Track): boolean",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "identifier",
						type: "string | Track",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "boolean",
			},
		],
		events: [],
		properties: [],
		params: [],
	},
	websockethandler: {
		title: "WebSocketHandler",
		description: "The WebSocketHandler class",
		summary: "",
		badges: ["class", "core", "websockethandler"],
		code: "// WebSocketHandler usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
	},
	handles: {
		title: "handles",
		description: "Manages Lavalink node connections and operations.",
		summary: "",
		badges: ["class", "core", "handles"],
		code: "// handles usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	playerstatemanager: {
		title: "PlayerStateManager",
		description:
			"Manages player states and voice connection handling for Lavalink players. This class handles: - Player state tracking and synchronization - Voice connection state management - Voice server and state update handling - Player-to-node mapping and assignment - Voice connection timeout and error handling",
		summary: "",
		badges: ["class", "core", "playerstatemanager"],
		code: "// PlayerStateManager usage example",
		methods: [
			{
				name: "destroy",
				signature: "destroy(): void",
				description: "",
				example: "",
				code: "",
				parameters: [],
				returns: "void",
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	nodemanager: {
		title: "NodeManager",
		description:
			"Manages Lavalink node connections and operations. This class handles: - Connection management to multiple Lavalink nodes - Load balancing and node selection strategies - REST API operations for track loading and player management - WebSocket event handling for real-time updates - Automatic failover and reconnection",
		summary: "",
		badges: ["class", "core", "nodemanager"],
		code: "// NodeManager usage example",
		methods: [
			{
				name: "destroy",
				signature: "destroy(): void",
				description: "",
				example: "",
				code: "",
				parameters: [],
				returns: "void",
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	trackresolver: {
		title: "TrackResolver",
		description: "The TrackResolver class",
		summary: "",
		badges: ["class", "core", "trackresolver"],
		code: "// TrackResolver usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
	},
	voicehandler: {
		title: "VoiceHandler",
		description: "The VoiceHandler class",
		summary: "",
		badges: ["class", "core", "voicehandler"],
		code: "// VoiceHandler usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
	},
	lavalinkext: {
		title: "lavalinkExt",
		description: "The lavalinkExt class",
		summary: "",
		badges: ["class", "extension", "lavalinkext"],
		code: "// lavalinkExt usage example",
		methods: [
			{
				name: "active",
				signature: "async active(alas: any): Promise<boolean>",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "alas",
						type: "any",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "Promise<boolean>",
			},
			{
				name: "onRegister",
				signature: "onRegister(context: ExtensionContext): void",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "context",
						type: "ExtensionContext",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "void",
			},
			{
				name: "onDestroy",
				signature: "async onDestroy(context: ExtensionContext): Promise<void>",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "context",
						type: "ExtensionContext",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "Promise<void>",
			},
			{
				name: "beforePlay",
				signature: "async beforePlay(context: ExtensionContext, payload: ExtensionPlayRequest): Promise<ExtensionPlayResponse>",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "context",
						type: "ExtensionContext",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "payload",
						type: "ExtensionPlayRequest",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "Promise<ExtensionPlayResponse>",
			},
			{
				name: "provideSearch",
				signature:
					"async provideSearch(_context: ExtensionContext, payload: ExtensionSearchRequest): Promise<SearchResult | null>",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "_context",
						type: "ExtensionContext",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "payload",
						type: "ExtensionSearchRequest",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "Promise<SearchResult | null>",
			},
			{
				name: "provideStream",
				signature: "async provideStream(context: ExtensionContext, payload: ExtensionStreamRequest): Promise<StreamInfo | null>",
				description: "",
				example: "",
				code: "",
				parameters: [
					{
						name: "context",
						type: "ExtensionContext",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "payload",
						type: "ExtensionStreamRequest",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "Promise<StreamInfo | null>",
			},
		],
		events: [],
		properties: [],
		params: [],
	},
	speechoptions: {
		title: "SpeechOptions",
		description: "Configuration options for voice recognition and speech processing. /",
		summary: "",
		badges: ["interface", "core", "speechoptions"],
		code: "// SpeechOptions usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	pcmstream: {
		title: "PcmStream",
		description:
			"Transform stream for processing PCM audio data. This stream handles the conversion and buffering of PCM audio data for speech recognition processing. /",
		summary: "",
		badges: ["class", "core", "pcmstream"],
		code: "// PcmStream usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	voiceext: {
		title: "voiceExt",
		description:
			"Voice extension for ZiPlayer that provides real-time speech recognition. This extension enables voice-to-text functionality by: - Listening to voice activity in Discord voice channels - Converting speech to text using Google Speech API - Supporting multiple languages and custom speech resolvers - Providing real-time voice event handling - Filtering and processing audio quality",
		summary: "",
		badges: ["class", "extension", "voiceext"],
		code: 'const voiceExt = new voiceExt(null, {\n  lang: "en-US",\n  ignoreBots: true,\n  minimalVoiceMessageDuration: 1,\n  client: discordClient\n});\n// Add to PlayerManager\nconst manager = new PlayerManager({\n  extensions: [voiceExt]\n});\n// Listen for voice events\nmanager.on("voiceCreate", (player, payload) => {\n  console.log(`${payload.userId} said: ${payload.content}`);\n});',
		methods: [
			{
				name: "active",
				signature: "active(alas: any): boolean",
				description:
					"Activates the voice extension with the provided context. This method handles the activation process: - Sets up the player and manager references - Binds the Discord client for voice events - Wraps the player's connect method to auto-attach voice handling - Attaches voice handling if already connected",
				example:
					"const success = voiceExt.active({\n  manager: playerManager,\n  client: discordClient,\n  player: playerInstance\n});\n/",
				code: "const success = voiceExt.active({\n  manager: playerManager,\n  client: discordClient,\n  player: playerInstance\n});",
				parameters: [
					{
						name: "alas",
						type: "any",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "`true` if activation was successful, `false` otherwise",
				},
			},
			{
				name: "attach",
				signature: "attach(client?: any, opts?: Partial<SpeechOptions>)",
				description:
					"Attaches voice recognition to a connected player. This method sets up voice recognition for a player that is already connected to a voice channel. It configures the speaking event handlers and sets up automatic cleanup when the player is destroyed.",
				example: 'voiceExt.attach(discordClient, {\n  lang: "en-US",\n  ignoreBots: false\n});\n/',
				code: 'voiceExt.attach(discordClient, {\n  lang: "en-US",\n  ignoreBots: false\n});',
				parameters: [
					{
						name: "client?",
						type: "any",
						description: "",
						optional: true,
						default: "",
						variation: "",
					},
					{
						name: "opts?",
						type: "Partial<SpeechOptions>",
						description: "",
						optional: true,
						default: "",
						variation: "",
					},
				],
				returns: "void",
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	lyricsoptions: {
		title: "LyricsOptions",
		description: "Configuration options for the lyrics extension. /",
		summary: "",
		badges: ["interface", "core", "lyricsoptions"],
		code: "// LyricsOptions usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	lyricsresult: {
		title: "LyricsResult",
		description: "Result object containing lyrics information and metadata. /",
		summary: "",
		badges: ["interface", "core", "lyricsresult"],
		code: "// LyricsResult usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	lyricsext: {
		title: "lyricsExt",
		description:
			"Lyrics extension for ZiPlayer that provides automatic lyrics fetching and synchronization. This extension automatically fetches and displays lyrics for playing tracks by: - Fetching lyrics from multiple providers (LRCLIB, Lyrics.ovh) - Supporting both plain text and LRC (synchronized) lyrics - Providing real-time line-by-line updates for synced lyrics - Automatically cleaning and sanitizing track titles for better matching - Emitting events for lyrics creation and updates",
		summary: "",
		badges: ["class", "extension", "lyricsext"],
		code: 'const lyricsExt = new lyricsExt(null, {\n  provider: "lrclib",\n  includeSynced: true,\n  autoFetchOnTrackStart: true\n});\n// Add to PlayerManager\nconst manager = new PlayerManager({\n  extensions: [lyricsExt]\n});\n// Listen for lyrics events\nmanager.on("lyricsCreate", (player, track, lyrics) => {\n  console.log(`Lyrics for ${track.title}: ${lyrics.text}`);\n});\nmanager.on("lyricsChange", (player, track, lyrics) => {\n  console.log(`Current line: ${lyrics.current}`);\n});',
		methods: [
			{
				name: "active",
				signature: "active(alas: any): boolean",
				description:
					"Activates the lyrics extension with the provided context. This method handles the activation process: - Sets up the player and manager references - Attaches track start event listeners for automatic lyrics fetching - Sets up cleanup handlers for track end and player destroy events",
				example: "const success = lyricsExt.active({\n  manager: playerManager,\n  player: playerInstance\n});\n/",
				code: "const success = lyricsExt.active({\n  manager: playerManager,\n  player: playerInstance\n});",
				parameters: [
					{
						name: "alas",
						type: "any",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "`true` if activation was successful, `false` otherwise",
				},
			},
			{
				name: "fetch",
				signature: "async fetch(track?: Track, override?: Partial<LyricsOptions>): Promise<LyricsResult | null>",
				description:
					"Fetches lyrics for a given track. This method attempts to fetch lyrics from configured providers: - First tries LRCLIB with artist and title - Falls back to LRCLIB with title only if no results - Finally tries Lyrics.ovh as a last resort - Supports both plain text and LRC (synchronized) lyrics",
				example:
					'const lyrics = await lyricsExt.fetch(track, {\n  provider: "lrclib",\n  includeSynced: true\n});\nif (lyrics) {\n  console.log(`Found ${lyrics.provider} lyrics: ${lyrics.text}`);\n  if (lyrics.synced) {\n    console.log("Synced lyrics available!");\n  }\n}\n/',
				code: 'const lyrics = await lyricsExt.fetch(track, {\n  provider: "lrclib",\n  includeSynced: true\n});\nif (lyrics) {\n  console.log(`Found ${lyrics.provider} lyrics: ${lyrics.text}`);\n  if (lyrics.synced) {\n    console.log("Synced lyrics available!");\n  }\n}',
				parameters: [
					{
						name: "track?",
						type: "Track",
						description: "",
						optional: true,
						default: "",
						variation: "",
					},
					{
						name: "override?",
						type: "Partial<LyricsOptions>",
						description: "",
						optional: true,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "Lyrics result object, or null if no lyrics found",
				},
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	pluginoptions: {
		title: "PluginOptions",
		description:
			"YouTube VM shim This allows the SABR stream to execute YouTube's custom JavaScript for deciphering signatures and generating tokens /",
		summary: "",
		badges: ["interface", "plugin", "pluginoptions"],
		code: "// PluginOptions usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	youtubeplugin: {
		title: "YouTubePlugin",
		description:
			"A plugin for handling YouTube audio content including videos, playlists, and search functionality. This plugin provides comprehensive support for: - YouTube video URLs (youtube.com, youtu.be, music.youtube.com) - YouTube playlist URLs and dynamic mixes - YouTube search queries - Audio stream extraction from YouTube videos - Related track recommendations",
		summary: "",
		badges: ["class", "plugin", "youtubeplugin"],
		code: 'const youtubePlugin = new YouTubePlugin();\n// Add to PlayerManager\nconst manager = new PlayerManager({\n  plugins: [youtubePlugin]\n});\n// Search for videos\nconst result = await youtubePlugin.search("Never Gonna Give You Up", "user123");\n// Get audio stream\nconst stream = await youtubePlugin.getStream(result.tracks[0]);',
		methods: [
			{
				name: "canHandle",
				signature: "canHandle(query: string): boolean",
				description: "Determines if this plugin can handle the given query.",
				example:
					'plugin.canHandle("https://www.youtube.com/watch?v=dQw4w9WgXcQ"); // true\nplugin.canHandle("Never Gonna Give You Up"); // true\nplugin.canHandle("spotify:track:123"); // false\n/',
				code: 'plugin.canHandle("https://www.youtube.com/watch?v=dQw4w9WgXcQ"); // true\nplugin.canHandle("Never Gonna Give You Up"); // true\nplugin.canHandle("spotify:track:123"); // false',
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "`true` if the plugin can handle the query, `false` otherwise",
				},
			},
			{
				name: "validate",
				signature: "validate(url: string): boolean",
				description: "Validates if a URL is a valid YouTube URL.",
				example:
					'plugin.validate("https://www.youtube.com/watch?v=dQw4w9WgXcQ"); // true\nplugin.validate("https://youtu.be/dQw4w9WgXcQ"); // true\nplugin.validate("https://spotify.com/track/123"); // false\n/',
				code: 'plugin.validate("https://www.youtube.com/watch?v=dQw4w9WgXcQ"); // true\nplugin.validate("https://youtu.be/dQw4w9WgXcQ"); // true\nplugin.validate("https://spotify.com/track/123"); // false',
				parameters: [
					{
						name: "url",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "`true` if the URL is a valid YouTube URL, `false` otherwise",
				},
			},
			{
				name: "search",
				signature: "async search(query: string, requestedBy: string): Promise<SearchResult>",
				description:
					"Searches for YouTube content based on the given query. This method handles both URL-based queries (direct video/playlist links) and text-based search queries. For URLs, it will extract video or playlist information. For text queries, it will perform a YouTube search and return up to 10 results.",
				example:
					'// Search by URL\nconst result = await plugin.search("https://www.youtube.com/watch?v=dQw4w9WgXcQ", "user123");\n// Search by text\nconst searchResult = await plugin.search("Never Gonna Give You Up", "user123");\nconsole.log(searchResult.tracks); // Array of Track objects\n/',
				code: '// Search by URL\nconst result = await plugin.search("https://www.youtube.com/watch?v=dQw4w9WgXcQ", "user123");\n// Search by text\nconst searchResult = await plugin.search("Never Gonna Give You Up", "user123");\nconsole.log(searchResult.tracks); // Array of Track objects',
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "requestedBy",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "A SearchResult containing tracks and optional playlist information",
				},
			},
			{
				name: "extractPlaylist",
				signature: "async extractPlaylist(url: string, requestedBy: string): Promise<Track[]>",
				description: "Extracts tracks from a YouTube playlist URL.",
				example:
					'const tracks = await plugin.extractPlaylist(\n  "https://www.youtube.com/playlist?list=PLrAXtmRdnEQy6nuLMOV8uM0bMq3MUfHc1",\n  "user123"\n);\nconsole.log(`Found ${tracks.length} tracks in playlist`);\n/',
				code: 'const tracks = await plugin.extractPlaylist(\n  "https://www.youtube.com/playlist?list=PLrAXtmRdnEQy6nuLMOV8uM0bMq3MUfHc1",\n  "user123"\n);\nconsole.log(`Found ${tracks.length} tracks in playlist`);',
				parameters: [
					{
						name: "url",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "requestedBy",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "An array of Track objects from the playlist",
				},
			},
			{
				name: "getStream",
				signature: "async getStream(track: Track, signal?: AbortSignal): Promise<StreamInfo>",
				description:
					"Retrieves the audio stream for a YouTube track. The plugin first attempts youtubei.js with a BotGuard WebPO token, then falls back to SABR if the youtubei.js download fails.",
				example:
					'const track = { id: "dQw4w9WgXcQ", title: "Never Gonna Give You Up", ... };\nconst streamInfo = await plugin.getStream(track);\nconsole.log(streamInfo.type); // "arbitrary"\nconsole.log(streamInfo.stream); // Readable stream\n/',
				code: 'const track = { id: "dQw4w9WgXcQ", title: "Never Gonna Give You Up", ... };\nconst streamInfo = await plugin.getStream(track);\nconsole.log(streamInfo.type); // "arbitrary"\nconsole.log(streamInfo.stream); // Readable stream',
				parameters: [
					{
						name: "track",
						type: "Track",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "signal?",
						type: "AbortSignal",
						description: "",
						optional: true,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "A StreamInfo object containing the audio stream and metadata",
				},
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	soundcloudplugin: {
		title: "SoundCloudPlugin",
		description:
			"A plugin for handling SoundCloud audio content including tracks, playlists, and search functionality. This plugin provides comprehensive support for: - SoundCloud track URLs (soundcloud.com) - SoundCloud playlist URLs - SoundCloud search queries - Audio stream extraction from SoundCloud tracks - Related track recommendations",
		summary: "",
		badges: ["class", "plugin", "soundcloudplugin"],
		code: 'const soundcloudPlugin = new SoundCloudPlugin();\n// Add to PlayerManager\nconst manager = new PlayerManager({\n  plugins: [soundcloudPlugin]\n});\n// Search for tracks\nconst result = await soundcloudPlugin.search("chill music", "user123");\n// Get audio stream\nconst stream = await soundcloudPlugin.getStream(result.tracks[0]);',
		methods: [
			{
				name: "canHandle",
				signature: "canHandle(query: string): boolean",
				description: "Determines if this plugin can handle the given query.",
				example:
					'plugin.canHandle("https://soundcloud.com/artist/track"); // true\nplugin.canHandle("chill music"); // true\nplugin.canHandle("spotify:track:123"); // false\n/',
				code: 'plugin.canHandle("https://soundcloud.com/artist/track"); // true\nplugin.canHandle("chill music"); // true\nplugin.canHandle("spotify:track:123"); // false',
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "`true` if the plugin can handle the query, `false` otherwise",
				},
			},
			{
				name: "validate",
				signature: "validate(url: string): boolean",
				description: "Validates if a URL is a valid SoundCloud URL.",
				example:
					'plugin.validate("https://soundcloud.com/artist/track"); // true\nplugin.validate("https://www.soundcloud.com/artist/track"); // true\nplugin.validate("https://youtube.com/watch?v=123"); // false\n/',
				code: 'plugin.validate("https://soundcloud.com/artist/track"); // true\nplugin.validate("https://www.soundcloud.com/artist/track"); // true\nplugin.validate("https://youtube.com/watch?v=123"); // false',
				parameters: [
					{
						name: "url",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "`true` if the URL is a valid SoundCloud URL, `false` otherwise",
				},
			},
			{
				name: "search",
				signature: "async search(query: string, requestedBy: string): Promise<SearchResult>",
				description:
					"Searches for SoundCloud content based on the given query. This method handles both URL-based queries (direct track/playlist links) and text-based search queries. For URLs, it will extract track or playlist information. For text queries, it will perform a SoundCloud search and return up to 10 results.",
				example:
					'// Search by URL\nconst result = await plugin.search("https://soundcloud.com/artist/track", "user123");\n// Search by text\nconst searchResult = await plugin.search("chill music", "user123");\nconsole.log(searchResult.tracks); // Array of Track objects\n/',
				code: '// Search by URL\nconst result = await plugin.search("https://soundcloud.com/artist/track", "user123");\n// Search by text\nconst searchResult = await plugin.search("chill music", "user123");\nconsole.log(searchResult.tracks); // Array of Track objects',
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "requestedBy",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "A SearchResult containing tracks and optional playlist information",
				},
			},
			{
				name: "getStream",
				signature: "async getStream(track: Track): Promise<StreamInfo>",
				description:
					"Retrieves the audio stream for a SoundCloud track. This method downloads the audio stream from SoundCloud using the track's URL. It handles the SoundCloud-specific download process and returns the stream in a format compatible with the player.",
				example:
					'const track = { id: "123", title: "Track Title", url: "https://soundcloud.com/artist/track", ... };\nconst streamInfo = await plugin.getStream(track);\nconsole.log(streamInfo.type); // "arbitrary"\nconsole.log(streamInfo.stream); // Readable stream\n/',
				code: 'const track = { id: "123", title: "Track Title", url: "https://soundcloud.com/artist/track", ... };\nconst streamInfo = await plugin.getStream(track);\nconsole.log(streamInfo.type); // "arbitrary"\nconsole.log(streamInfo.stream); // Readable stream',
				parameters: [
					{
						name: "track",
						type: "Track",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "A StreamInfo object containing the audio stream and metadata",
				},
			},
			{
				name: "extractPlaylist",
				signature: "async extractPlaylist(url: string, requestedBy: string): Promise<Track[]>",
				description: "Extracts tracks from a SoundCloud playlist URL.",
				example:
					'const tracks = await plugin.extractPlaylist(\n  "https://soundcloud.com/artist/sets/playlist-name",\n  "user123"\n);\nconsole.log(`Found ${tracks.length} tracks in playlist`);\n/',
				code: 'const tracks = await plugin.extractPlaylist(\n  "https://soundcloud.com/artist/sets/playlist-name",\n  "user123"\n);\nconsole.log(`Found ${tracks.length} tracks in playlist`);',
				parameters: [
					{
						name: "url",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "requestedBy",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "An array of Track objects from the playlist",
				},
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	spotifytrack: {
		title: "spotifyTrack",
		description: "The spotifyTrack interface",
		summary: "",
		badges: ["interface", "core", "spotifytrack"],
		code: "// spotifyTrack usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
	},
	spotifypreview: {
		title: "spotifyPreview",
		description: "The spotifyPreview interface",
		summary: "",
		badges: ["interface", "core", "spotifypreview"],
		code: "// spotifyPreview usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
	},
	spotifyplugin: {
		title: "SpotifyPlugin",
		description:
			"A minimal Spotify plugin for metadata extraction and display purposes. This plugin provides support for: - Spotify track URLs/URIs (spotify:track:...) - Spotify playlist URLs/URIs (spotify:playlist:...) - Spotify album URLs/URIs (spotify:album:...) - Metadata extraction using Spotify's public oEmbed endpoint **Important Notes:** - This plugin does NOT provide audio streams (player is expected to redirect/fallback upstream) - This plugin does NOT expand playlists/albums (no SDK; oEmbed doesn't enumerate items) - This plugin only provides display metadata for Spotify content",
		summary: "",
		badges: ["class", "plugin", "spotifyplugin"],
		code: 'const spotifyPlugin = new SpotifyPlugin();\n// Add to PlayerManager\nconst manager = new PlayerManager({\n  plugins: [spotifyPlugin]\n});\n// Get metadata for a Spotify track\nconst result = await spotifyPlugin.search("spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "user123");\nconsole.log(result.tracks[0].metadata); // Contains Spotify metadata',
		methods: [
			{
				name: "canHandle",
				signature: "canHandle(query: string): boolean",
				description: "Determines if this plugin can handle the given query.",
				example:
					'plugin.canHandle("spotify:track:4iV5W9uYEdYUVa79Axb7Rh"); // true\nplugin.canHandle("https://open.spotify.com/track/4iV5W9uYEdYUVa79Axb7Rh"); // true\nplugin.canHandle("youtube.com/watch?v=123"); // false\n/',
				code: 'plugin.canHandle("spotify:track:4iV5W9uYEdYUVa79Axb7Rh"); // true\nplugin.canHandle("https://open.spotify.com/track/4iV5W9uYEdYUVa79Axb7Rh"); // true\nplugin.canHandle("youtube.com/watch?v=123"); // false',
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "`true` if the query is a Spotify URL/URI, `false` otherwise",
				},
			},
			{
				name: "validate",
				signature: "validate(url: string): boolean",
				description: "Validates if a URL/URI is a valid Spotify URL/URI.",
				example:
					'plugin.validate("spotify:track:4iV5W9uYEdYUVa79Axb7Rh"); // true\nplugin.validate("https://open.spotify.com/track/4iV5W9uYEdYUVa79Axb7Rh"); // true\nplugin.validate("https://youtube.com/watch?v=123"); // false\n/',
				code: 'plugin.validate("spotify:track:4iV5W9uYEdYUVa79Axb7Rh"); // true\nplugin.validate("https://open.spotify.com/track/4iV5W9uYEdYUVa79Axb7Rh"); // true\nplugin.validate("https://youtube.com/watch?v=123"); // false',
				parameters: [
					{
						name: "url",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "`true` if the URL/URI is a valid Spotify URL/URI, `false` otherwise",
				},
			},
			{
				name: "search",
				signature: "async search(query: string, requestedBy: string): Promise<SearchResult>",
				description:
					"Extracts metadata from Spotify URLs/URIs using the oEmbed API. This method handles Spotify track, playlist, and album URLs/URIs by fetching display metadata from Spotify's public oEmbed endpoint. It does not provide audio streams or expand playlists/albums.",
				example:
					'// Extract track metadata\nconst result = await plugin.search("spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "user123");\nconsole.log(result.tracks[0].metadata); // Contains Spotify metadata\n// Extract playlist metadata\nconst playlistResult = await plugin.search("https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M", "user123");\nconsole.log(playlistResult.tracks[0].metadata.kind); // "playlist"\n/',
				code: '// Extract track metadata\nconst result = await plugin.search("spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "user123");\nconsole.log(result.tracks[0].metadata); // Contains Spotify metadata\n// Extract playlist metadata\nconst playlistResult = await plugin.search("https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M", "user123");\nconsole.log(playlistResult.tracks[0].metadata.kind); // "playlist"',
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "requestedBy",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "A SearchResult containing a single track with metadata (no audio stream)",
				},
			},
			{
				name: "extractPlaylist",
				signature: "async extractPlaylist(_input: string, _requestedBy: string): Promise<Track[]>",
				description:
					"Extracts tracks from a Spotify playlist URL. **Note:** This method is not implemented as this plugin does not support playlist expansion. It always returns an empty array.",
				example:
					'const tracks = await plugin.extractPlaylist("spotify:playlist:123", "user123");\nconsole.log(tracks); // [] - empty array\n/',
				code: 'const tracks = await plugin.extractPlaylist("spotify:playlist:123", "user123");\nconsole.log(tracks); // [] - empty array',
				parameters: [
					{
						name: "_input",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "_requestedBy",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "An empty array (playlist expansion not supported)",
				},
			},
			{
				name: "getStream",
				signature: "async getStream(_track: Track): Promise<StreamInfo>",
				description:
					"Attempts to get an audio stream for a Spotify track. **Note:** This method always throws an error as this plugin does not support audio streaming. The player is expected to redirect to other plugins or use fallback mechanisms for actual audio playback.",
				example:
					'try {\n  const stream = await plugin.getStream(track);\n} catch (error) {\n  console.log(error.message); // "Spotify streaming is not supported by this plugin"\n}\n/',
				code: 'try {\n  const stream = await plugin.getStream(track);\n} catch (error) {\n  console.log(error.message); // "Spotify streaming is not supported by this plugin"\n}',
				parameters: [
					{
						name: "_track",
						type: "Track",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: "Promise<StreamInfo>",
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	ttspluginoptions: {
		title: "TTSPluginOptions",
		description: "Configuration options for the TTSPlugin. /",
		summary: "",
		badges: ["interface", "plugin", "ttspluginoptions"],
		code: "// TTSPluginOptions usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	ttsconfig: {
		title: "TTSConfig",
		description: "Internal configuration for TTS processing. /",
		summary: "",
		badges: ["interface", "core", "ttsconfig"],
		code: "// TTSConfig usage example",
		methods: [],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
	ttsplugin: {
		title: "TTSPlugin",
		description:
			"A plugin for Text-to-Speech (TTS) functionality. This plugin provides support for: - Converting text to speech using Google TTS - Custom TTS providers via the createStream hook - Multiple language support - Configurable speech rate (normal/slow) - TTS query parsing with language and speed options - Accurate duration analysis by generating sample audio",
		summary: "",
		badges: ["class", "plugin", "ttsplugin"],
		code: 'const ttsPlugin = new TTSPlugin({\n  defaultLang: "en",\n  slow: false\n});\n// Add to PlayerManager\nconst manager = new PlayerManager({\n  plugins: [ttsPlugin]\n});\n// Search for TTS content\nconst result = await ttsPlugin.search("tts:Hello world", "user123");\nconst stream = await ttsPlugin.getStream(result.tracks[0]);\n// Custom TTS provider\nconst customTTSPlugin = new TTSPlugin({\n  defaultLang: "en",\n  createStream: async (text, ctx) => {\n    // Custom TTS implementation\n    return customTTSProvider.synthesize(text, ctx.lang);\n  }\n});',
		methods: [
			{
				name: "canHandle",
				signature: "canHandle(query: string): boolean",
				description: "Determines if this plugin can handle the given query.",
				example: 'plugin.canHandle("tts:Hello world"); // true\nplugin.canHandle("youtube.com/watch?v=123"); // false\n/',
				code: 'plugin.canHandle("tts:Hello world"); // true\nplugin.canHandle("youtube.com/watch?v=123"); // false',
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: '`true` if the query starts with "tts:" or "say ", `false` otherwise',
				},
			},
			{
				name: "search",
				signature: "async search(query: string, requestedBy: string): Promise<SearchResult>",
				description:
					"Creates a TTS track from the given query. This method parses TTS queries and creates a track that can be played as audio. It supports various query formats including language and speed specifications.",
				example:
					'// Basic TTS\nconst result = await plugin.search("tts:Hello world", "user123");\n// TTS with specific language\nconst result2 = await plugin.search("tts:en:Hello world", "user123");\n// TTS with language and slow speed\nconst result3 = await plugin.search("tts:en:true:Hello world", "user123");\n// Using "say" prefix\nconst result4 = await plugin.search("say Hello world", "user123");\n/',
				code: '// Basic TTS\nconst result = await plugin.search("tts:Hello world", "user123");\n// TTS with specific language\nconst result2 = await plugin.search("tts:en:Hello world", "user123");\n// TTS with language and slow speed\nconst result3 = await plugin.search("tts:en:true:Hello world", "user123");\n// Using "say" prefix\nconst result4 = await plugin.search("say Hello world", "user123");',
				parameters: [
					{
						name: "query",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
					{
						name: "requestedBy",
						type: "string",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "A SearchResult containing a single TTS track",
				},
			},
			{
				name: "getStream",
				signature: "async getStream(track: Track): Promise<StreamInfo>",
				description:
					"Generates an audio stream for a TTS track. This method converts the text in the track to speech using either the custom TTS provider (if configured) or the built-in Google TTS service. It handles various return types from custom providers and ensures proper stream formatting.",
				example:
					'const track = { id: "tts-123", title: "TTS: Hello world", ... };\nconst streamInfo = await plugin.getStream(track);\nconsole.log(streamInfo.type); // "arbitrary"\nconsole.log(streamInfo.stream); // Readable stream with audio\n/',
				code: 'const track = { id: "tts-123", title: "TTS: Hello world", ... };\nconst streamInfo = await plugin.getStream(track);\nconsole.log(streamInfo.type); // "arbitrary"\nconsole.log(streamInfo.stream); // Readable stream with audio',
				parameters: [
					{
						name: "track",
						type: "Track",
						description: "",
						optional: false,
						default: "",
						variation: "",
					},
				],
				returns: {
					type: "any",
					description: "A StreamInfo object containing the audio stream",
				},
			},
		],
		events: [],
		properties: [],
		params: [],
		returns: null,
	},
};

export const apiContentSummary = {
	totalItems: 26,
	byType: {
		class: 17,
		interface: 9,
	},
	byModule: {
		core: 17,
		extension: 3,
		plugin: 6,
	},
	withJSDoc: 18,
	withExamples: 0,
	withReturns: 0,
	withParams: 0,
};

// Summary:
// - Total items: 26
// - Classes: 17
// - Interfaces: 9
// - Modules: 0
// - Core: 17
// - Plugins: 6
// - Extensions: 3
// - With JSDoc: 18
// - With Examples: 0
// - With @returns: 0
// - With @param: 0
